export const products = [
  {
    id: 1,
    title: "Master Modern Laptop Keyboard",
    photo: {
      thumbnail: "https://example.com/images/keyboard-thumbnail.jpg",
      cover: "https://example.com/images/keyboard-cover.jpg",
    },
    quantity: 50,
    price: 120.99,
    stock: "In Stock",
    discount: 10,
    description: "A high-quality mechanical keyboard with RGB backlight.",
    category: "Electronics",
  },
  {
    id: 2,
    title: "Wireless Mouse",
    photo: {
      thumbnail: "https://example.com/images/mouse-thumbnail.jpg",
      cover: "https://example.com/images/mouse-cover.jpg",
    },
    quantity: 100,
    price: 35.49,
    stock: "In Stock",
    discount: 5,
    description: "Ergonomic wireless mouse with adjustable DPI settings.",
    category: "Accessories",
  },
  {
    id: 3,
    title: "Gaming Headset",
    photo: {
      thumbnail: "https://example.com/images/headset-thumbnail.jpg",
      cover: "https://example.com/images/headset-cover.jpg",
    },
    quantity: 25,
    price: 75.0,
    stock: "Out of Stock",
    discount: 15,
    description: "High-fidelity gaming headset with noise cancellation.",
    category: "Audio",
  },
  {
    id: 4,
    title: "Smartphone Stand",
    photo: {
      thumbnail: "https://example.com/images/stand-thumbnail.jpg",
      cover: "https://example.com/images/stand-cover.jpg",
    },
    quantity: 200,
    price: 12.99,
    stock: "In Stock",
    discount: 0,
    description: "Adjustable smartphone stand for hands-free usage.",
    category: "Accessories",
  },
  {
    id: 5,
    title: "Bluetooth Speaker",
    photo: {
      thumbnail: "https://example.com/images/speaker-thumbnail.jpg",
      cover: "https://example.com/images/speaker-cover.jpg",
    },
    quantity: 75,
    price: 45.0,
    stock: "In Stock",
    discount: 10,
    description: "Portable Bluetooth speaker with powerful bass.",
    category: "Audio",
  },
  {
    id: 6,
    title: "Laptop Cooling Pad",
    photo: {
      thumbnail: "https://example.com/images/coolingpad-thumbnail.jpg",
      cover: "https://example.com/images/coolingpad-cover.jpg",
    },
    quantity: 40,
    price: 25.99,
    stock: "In Stock",
    discount: 20,
    description: "Efficient laptop cooling pad with dual fans.",
    category: "Electronics",
  },
  {
    id: 7,
    title: "USB-C Hub",
    photo: {
      thumbnail: "https://example.com/images/usbhub-thumbnail.jpg",
      cover: "https://example.com/images/usbhub-cover.jpg",
    },
    quantity: 150,
    price: 29.99,
    stock: "In Stock",
    discount: 5,
    description: "Multiport USB-C hub with HDMI, USB-A, and SD card slots.",
    category: "Accessories",
  },
  {
    id: 8,
    title: "Ergonomic Office Chair",
    photo: {
      thumbnail: "https://example.com/images/chair-thumbnail.jpg",
      cover: "https://example.com/images/chair-cover.jpg",
    },
    quantity: 30,
    price: 199.99,
    stock: "In Stock",
    discount: 25,
    description: "Comfortable ergonomic chair with adjustable features.",
    category: "Furniture",
  },
];
